@startuml
skinparam shadowing false

class Spielplatz {
  +ID:UUID
  -bezeichnung:String
  -anzahlKinder:int
  -status:Status
  -sauberkeit:SauberkeitStatus
  -standort:Standort
  -information:String
  +List<Geraet> geraete
  +List<Benutzer> angemeldeteBenutzer

  +Spielplatz()
  +getBezeichnung():String
  +setBezeichnung(String Bezeichnung)
  +getStatus():Status
  +setStatus(Status Status)
  +getAnzahlKinder():int
  +setAnzahlKinder(int AnzahlKinder)
  +getStandort():Standort
  +setStandort(Standort standort)
  +getID():UUID
  +setID(UUID ID)
  +getInformation():String
  +setInformation(String information)
  +getGeraet(String geraeteName):Geraet
}

class Standort{
 -strassenname:String
 -hausnummer:int
 -postleitzahl:int
 -stadtname:String

 +getStrassenname():String
 +setStrassenname(String strassenname)
 +getHausnummer():int
 +setHausnummer(int hausnummer)
 +getPostleitzahl():int
 +setPostleitzahl(int postleitzahl)
 +getStadtname():String
 +setStadtname(String stadtname)
}

class Geraet{
-spielplatzID:UUID
-bezeichnung:String
-geraeteStatus:GeraeteStatus
-beschreibung:String

+Geraet(UUID spielplatzID, String bezeichnung, GeraeteStatus status, String beschreibung)
+getGeraeteStatus():GeraeteStatus
+setGeraeteStatus(GeraeteStatus geraeteStatus)
+getSpielplatzID():UUID
+setSpielplatzID(UUID spielplatzID)
+getBezeichnung():String
+setBezeichnung(String bezeichnung)
+getBeschreibung():String
+setBeschreibung(String beschreibung)
}
enum GeraeteStatus{
    inTaktesGeraet,
    verschmutztesGeraet,
    kaputtesGeraet,
    verletzungsgefahr
}
enum Status{
 offen,
 gutBesucht,
 voll,
 ueberfuellt
}
enum SauberkeitStatus{
    sauber,
    leichtVerschmutzt,
    starkVerschmutzt
}
enum Zugriff{
 administrator,
 moderator,
 benutzer
}

abstract class Profil{
#benutzername:String
#passwort:String
#email:String
#zugriff:Zugriff

+getBenutzername():String
+setBenutzername(String benutzername)
+getPasswort():String
+setPasswort(String passwort)
+getEmail():String
+setEmail(String email)
+PasswortAendern(Profil profil,String altesPasswort)
}

class Benutzer{
#eigeneKinder:int
#aufenthaltsort:Standort
#List<Spielplatz>spielplatzFavoriten
#List<Benutzer> freunde
#aktuellerSpielplatz:UUID;

+Benutzer()
+Benutzer(String benutzername, String email, String passwort, int anzahlKinder)
+getSpielplatzFavoriten():List<Spielplatz>
+setSpielplatzFavoriten(List<Spielplatz> spielplatzFavoriten)
+getEigeneKinder():int
+setEigeneKinder(int eigeneKinder)
+getAufenthaltsort():Standort
+setAufenthaltsort(Standort aufenthaltsort)
+getFreunde():List<Benutzer>
+setFreunde(List<Benutzer> freunde)
+freundHinzufuegen(Benutzer neuerFreund)
+freundEntfernen(Benutzer freund)
+spielplatzFavoritHinzufuegen(Spielplatz neuerSpielplatz)
+spielplatzFavoritEntfernen(Spielplatz spielplatz)
+getAktuellenSpielplatz(List<Spielplatz> alleSpielplaetze):Spielplatz
+setAktuellenSpielplatz(UUID spielplatzID)
+geraetMelden(String geraetName, List<Spielplatz> alleSpielplaetze)
}

class Admin{
+Admin(String benutzername, String passwort, String email)
+benutzerZuModerator(Benutzer benutzer):Moderator
+moderatorZuBenutzer(Moderator moderator):Benutzer
+passwortZuruecksetzen(Profil profil)
+spielplatzLoeschen(List<Spielplatz> spielplatzListe,Spielplatz spielplatz)
+geraeteLoeschen(List<Geraet> geraete, Geraet geraet)
}

class Moderator{
+Moderator(String benutzername, String email, String passwort, int anzahlKinder, Standort aufenthaltsort)
+geraeteStatusAendern(Geraet geraet, GeraeteStatus neuerGeraeteStatus)
}

Profil <|--Benutzer
Profil <|--Admin
Benutzer <|--Moderator
Spielplatz "1" *-- "1" Standort
Spielplatz "1" *-- "1" Status
Spielplatz "1" *-- "1" SauberkeitStatus
Spielplatz "1" --{ "0..n" Benutzer
Profil "1" o-- Standort
Zugriff "1" --* "1" Profil
Geraet "0..n" }-- "1" Spielplatz
Geraet "1" *-- "1" GeraeteStatus
@enduml
