@startuml
skinparam shadowing false

class Spielplatz {
  +ID:UUID
  -bezeichnung:String
  -status:Status
  -sauberkeit:SauberkeitStatus
  -standort:Standort
  -information:String
  -anzahlKinder:int
  -kapazitaetSpielplatz:int
  +List<Geraet> geraete
  +List<Erweiterung> erweiterungen
  +List<Benutzer> angemeldeteBenutzer

  +Spielplatz()
  +Spielplatz(String bezeichnung, Status status, SauberkeitStatus sauberkeit, String information, int anzahlKinder)
  +setErweiterungen(List<Erweiterung> erweiterungen)
  +getErweiterungen():List<Erweiterung>
  +getBezeichnung():String
  +setBezeichnung(String Bezeichnung)
  +getStatus():Status
  +setStatus(Status Status)
  +getAnzahlKinder():int
  +setAnzahlKinder(int AnzahlKinder)
  +getStandort():Standort
  +setStandort(Standort standort)
  +getID():UUID
  +setID(UUID ID)
  +getSauberkeit():SauberkeitStatus
  +setSauberkeit(SauberkeitStatus sauberkeit)
  +getInformation():String
  +setInformation(String information)
  +getKapazitaetSpielplatz():int
  +setKapazitaetSpielplatz(int kapazitaetSpielplatz)
  +getGeraet(String geraeteName):Geraet
  +pruefeStatus()
  +aktualisiereSpielplatzKapazitaet()
}

class Standort{
 -name:String
 -strassenname:String
 -hausnummer:int
 -postleitzahl:int
 -stadtname:String
 -stadtteil:String

 +Standort(int hausnummer, String strassenname, int postleitzahl, String stadtname, String name, String stadtteil)
 +getStrassenname():String
 +setStrassenname(String strassenname)
 +getHausnummer():int
 +setHausnummer(int hausnummer)
 +getPostleitzahl():int
 +setPostleitzahl(int postleitzahl)
 +getStadtname():String
 +setStadtname(String stadtname)
 +getName():String
 +setName(String name)
 +getStadtteil:String
 +setStadtteil(String stadtteil)
}

class Geraet{
-spielplatzID:UUID
-bezeichnung:String
-geraeteStatus:GeraeteStatus
-beschreibung:String

+Geraet(UUID spielplatzID, String bezeichnung, GeraeteStatus status, String beschreibung,int kapazitaetGeraet)
+getGeraeteStatus():GeraeteStatus
+setGeraeteStatus(GeraeteStatus geraeteStatus)
+getSpielplatzID():UUID
+setSpielplatzID(UUID spielplatzID)
+getBezeichnung():String
+setBezeichnung(String bezeichnung)
+getBeschreibung():String
+setBeschreibung(String beschreibung)
+getKapazitaetGeraet():int
+setKapazitaetGeraet(int kapazitaetGeraet)
}

abstract class Profil{
#benutzername:String
#passwort:String
#email:String
#zugriff:Zugriff
#istEingeloggt:boolean

+getBenutzername():String
+setBenutzername(String benutzername)
+getPasswort():String
+setPasswort(String passwort)
+getEmail():String
+setEmail(String email)
+setIstEingeloggt(boolean istEingeloggt)
+getIstEingeloggt():boolean
+PasswortAendern(Profil profil,String altesPasswort,String neuesPasswort)
+removeProfil(Profil profil,String benutzername)
+profilVerwalten(Profil profil, Profil neuerProfilEintrag)
+login(String benutzername,String password, List<Profil> benutzerListe):String
+logout(List<Profil> benutzerListe):String
+passwordVergessen(List<Profil> profilListe
}

class Benutzer{
#eigeneKinder:int
#aufenthaltsort:Standort
#List<Spielplatz>spielplatzFavoriten
#List<Benutzer> freunde
#aktuellerSpielplatz:UUID;

+Benutzer()
+Benutzer(String benutzername, String email, String passwort, int anzahlKinder)
+getSpielplatzFavoriten():List<Spielplatz>
+setSpielplatzFavoriten(List<Spielplatz> spielplatzFavoriten)
+getEigeneKinder():int
+setEigeneKinder(int eigeneKinder)
+getAufenthaltsort():Standort
+setAufenthaltsort(Standort aufenthaltsort)
+getFreunde():List<Benutzer>
+setFreunde(List<Benutzer> freunde)
+freundHinzufuegen(Benutzer neuerFreund)
+freundEntfernen(Benutzer freund)
+spielplatzFavoritHinzufuegen(Spielplatz neuerSpielplatz)
+spielplatzFavoritEntfernen(Spielplatz spielplatz)
+getAktuellenSpielplatz(List<Spielplatz> alleSpielplaetze):Spielplatz
+setAktuellenSpielplatz(UUID spielplatzID)
+geraetMelden(String geraetName, List<Spielplatz> alleSpielplaetze)
}

class Admin{
+Admin(String benutzername, String passwort, String email)
+benutzerZuModerator(Benutzer benutzer):Moderator
+moderatorZuBenutzer(Moderator moderator):Benutzer
+passwortZuruecksetzen(Profil profil)
+spielplatzLoeschen(List<Spielplatz> spielplatzListe,Spielplatz spielplatz)
+geraeteLoeschen(List<Geraet> geraete, Geraet geraet)
}

class Moderator{
+Moderator(String benutzername, String email, String passwort, int anzahlKinder, Standort aufenthaltsort)
+geraetHinzufuegen(Spielplatz spielplatz, Geraet geraet)
+geraetEntfernen(Spielplatz spielplatz, Geraet geraet
+geraeteStatusAendern(Geraet geraet, GeraeteStatus neuerGeraeteStatus)
+spielplatzHinzufuegen(List<Spielplatz> alleSpielplaetze, Spielplatz spielplatz)
+spielplatzEntfernen(List<Spielplatz> alleSpielplaetze, Spielplatz spielplatz)
+erweiterungHinzufuegen(Erweiterung erweiterung, Spielplatz spielplatz)
+erweiterungEntfernen(Erweiterung erweiterung, Spielplatz spielplatz)
+spielplatzVerwalten(Spielplatz spielplatz, Spielplatz neuerSpielplatzEintrag)
}

class Passwort{
+passwortGenerator():String
}

class Mail{
+versendeEmailPasswortVergessen(Profil profil, String neuesPasswort)
}

class Restaurant{
-HashMap<String, Double> speisekarte
-telefonNummer:String
-hatWickeltisch:boolean
-essenAbholbar:boolean
-essenLieferbar:boolean

+Restaurant(int anzahlPersonen, String bezeichnung,String telefonNummer)
+Restaurant(int anzahlPersonen, String bezeichnung,String telefonNummer, boolean hatWickeltisch
                                  ,boolean essenAbholbar,boolean essenLieferbar)
+fuegeSpeiseHinzu(String speisenName, Double preis)
+entferneSpeise(String speisenName)
+zeigeSpeisekarteAn()
+getHatWickeltisch():boolean
+setHatWickeltisch(boolean hatWickeltisch)
+getEssenAbholbar():boolean
+setEssenAbholbar(boolean essenAbholbar)
+getEssenLieferbar():boolean
+setEssenLieferbar(boolean essenLieferbar)
+getTelefonNummer():String
+setTelefonNummer(String telefonNummer)
+wickelTisch():String
+toilettenGang():String
+haendeWaschen():String
+essenGehen():String
+essenBestellenUndAbholen():String
+essenLiefern():String
}

abstract class Erweiterung{
#bezeichnung:String
#personenAnzahl:int

+getBezeichnung():String
+setBezeichnung(String bezeichnung)
+getPersonenAnzahl:int
+setPersonenAnzahl(int personenAnzahl)
}

class Sitzgelegenheit{
+Sitzgelegenheit(String bezeichnung, int personenAnzahl)
+sitzen():String
}

class Toilette{
-hatWickeltisch:boolean

+Toilette(int anzahlPersonen)
+Toilette(int anzahlPersonen, boolean hatWickeltisch)
+getHatWickeltisch():boolean
+setHatWickeltisch(boolean hatWickeltisch)
+toilettenGang():String
+haendeWaschen():String
+wickelTisch():String
}

enum GeraeteStatus{
    inTaktesGeraet,
    verschmutztesGeraet,
    kaputtesGeraet,
    verletzungsgefahr,
    zuPruefen
}
enum Status{
 offen,
 gutBesucht,
 voll,
 ueberfuellt
}
enum SauberkeitStatus{
    sauber,
    leichtVerschmutzt,
    starkVerschmutzt
}
enum Zugriff{
 administrator,
 moderator,
 benutzer
}

Profil <|--Benutzer
Profil <|--Admin
Benutzer <|--Moderator
Erweiterung <|-- Restaurant
Erweiterung <|-- Sitzgelegenheit
Erweiterung <|-- Toilette

Spielplatz "1" *-- "1" Standort
Spielplatz "1" *-- "1" Status
Spielplatz "1" *-- "1" SauberkeitStatus

Spielplatz "1" --{ "0..n" Benutzer
Profil "1" o-- Standort
Zugriff "1" --* "1" Profil
Passwort "1" --* "1" Profil
Geraet "0..n" }-- "1" Spielplatz
Geraet "1" *-- "1" GeraeteStatus

Erweiterung "0..n" }-- "1" Spielplatz
@enduml
