CREATE TABLE if NOT EXISTS SPIELPLATZ(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
BEZEICHNUNG VARCHAR(255),
STATUS ENUM('OFFEN','GUTBESUCHT','VOLL','UEBERFUELLT'),
SAUBERKEIT ENUM('SAUBER','LEICHTVERSCHMUTZT','STARKVERSCHMUTZT'),
STRASSENNAME VARCHAR(255),
HAUSNUMMER SMALLINT(4),
POSTLEITZAHL SMALLINT(10),
STADTNAME VARCHAR(255),
STADTTEIL VARCHAR(255),
INFORMATION VARCHAR(255),
ANZAHLKINDER SMALLINT(20),
KAPAZITAETSPIELPLATZ SMALLINT(255)
);
CREATE TABLE if NOT EXISTS GERAET(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
BEZEICHNUNG VARCHAR(255),
GERAETESTATUS ENUM('INTAKTESGERAET','VERSCHMUTZTESGERAET','KAPPUTTESGERAET','VERLETZUNGSGEFAHR','ZUPRUEFEN'),
BESCHREIBUNG VARCHAR (255),
);
CREATE TABLE if NOT EXISTS PROFIL(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
BENUTZERNAME VARCHAR (255),
PASSWORT VARCHAR (255),
EMAIL VARCHAR (255),
ZUGRIFF ENUM('ADMINISTRATOR','MODERATOR','BENUTZER'),
ISTEINGELOGGT BOOLEAN,
);
CREATE TABLE if NOT EXISTS BENUTZER(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
EIGENEKINDER SMALLINT (2),
STRASSENNAME VARCHAR(255),
HAUSNUMMER SMALLINT(4),
POSTLEITZAHL SMALLINT(10),
STADTNAME VARCHAR(255),
STADTTEIL VARCHAR(255),
);

CREATE TABLE if NOT EXISTS ERWEITERUNG(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
BEZEICHNUNG VARCHAR (255),
PERSONENANZAHL SMALLINT (4),
);

CREATE TABLE if NOT EXISTS RESTAURANT(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
HASHMAP VARCHAR (255),
TELEFONNUMMER VARCHAR (255),
HATWICKELTISCH BOOLEAN,
ESSENABHOLBAR BOOLEAN,
ESSENLIEFERBAR BOOLEAN,
);
CREATE TABLE if NOT EXISTS TOILETTE(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
HATWICKELTISCH BOOLEAN,
HATTEST BOOLEAN,
);