CREATE TABLE if NOT EXISTS SPIELPLATZ(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
BEZEICHNUNG VARCHAR(255),
STATUS ENUM(OFFEN,GUTBESUCHT,VOLL,UEBERFUELLT),
SAUBERKEIT ENUM(SAUBER,LEICHTVERSCHMUTZT,STARKVERSCHMUTZT),
STRASSENNAME VARCHAR(255),
HAUSNUMMER SMALLINT(4),
POSTLEITZAHL SMALLINT(10),
STADTNAME VARCHAR(255),
STADTTEIL VARCHAR(255),
INFORMATION VARCHAR(255),
ANZAHLKINDER SMALLINT(20),
KAPAZITAETSPIELPLATZ SMALLINT(255)
);
